### ISSUE TITLE
Move repo to wordpress organization

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/wporg-plugin-guidelines#58]
@pento - Would you be willing to assist in moving this repo to the @wordpress organization. 

@Ipstenu - Please add @pento as an admin to this repo so that he can move it.

**Comment by Ipstenu** [comment]
Invite sent (I hope....)

**Comment by pento** [comment]
Oh, hrrm. Because it's on a personal repo, you need to transfer it to me, then I can transfer it to the WordPress org.

**Comment by Ipstenu** [comment]
DONE!
